title: "Shilla Solanki"
logo: "/images/pink-panther-clipart-9b.JPG"
description: "AnalyticSleuth - My GitHub Portfolio"
repository_url: "https://github.com/AnalyticSleuth/AnalyticSleuth"
show_downloads: true
theme: jekyll-theme-minimal
